ra145979: ConversorBase.c ConversorBase.h Montador.c Montador.h readASM.h readASM.c main.c
	gcc -o ra145979 ConversorBase.c ConversorBase.h  Montador.c Montador.h  readASM.h readASM.c main.c -lm -Wall

